services:
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - VITE_API_URL=https://wcz3qr33kmjvzotdqt65efniv40kokon.lambda-url.us-east-2.on.aws
    container_name: frontend-prod
    restart: always
    ports:
      - 3000:3000
    networks:
      - network
networks:
  network:
