FROM node:20-alpine as builder
WORKDIR /app
COPY . .
ARG VITE_API_URL
ENV VITE_API_URL $VITE_API_URL
RUN npm install
RUN npm run build

FROM nginx:1.25.4-alpine-slim as prod
COPY --from=builder /app/dist /usr/share/nginx/html
#COPY --from=builder /app/api /usr/share/nginx/html
COPY nginx.conf  /etc/nginx/conf.d
EXPOSE 3000
CMD echo "App running at: http://localhost:3000" && (nginx -g 'daemon off;')